FROM python:3.10

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY requirements.txt requirements.txt

# RUN pip3 install -r requirements.txt

# COPY . .

# CMD ["env", "FLASK_APP=app/__main__.py", "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
